/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimingRouteImport } from './routes/timing'
import { Route as ParticipantsRouteImport } from './routes/participants'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results/index'
import { Route as ResultsParticipantIdRouteImport } from './routes/results/$participantId'

const TimingRoute = TimingRouteImport.update({
  id: '/timing',
  path: '/timing',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsParticipantIdRoute = ResultsParticipantIdRouteImport.update({
  id: '/results/$participantId',
  path: '/results/$participantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/participants': typeof ParticipantsRoute
  '/timing': typeof TimingRoute
  '/results/$participantId': typeof ResultsParticipantIdRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/participants': typeof ParticipantsRoute
  '/timing': typeof TimingRoute
  '/results/$participantId': typeof ResultsParticipantIdRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/participants': typeof ParticipantsRoute
  '/timing': typeof TimingRoute
  '/results/$participantId': typeof ResultsParticipantIdRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/participants'
    | '/timing'
    | '/results/$participantId'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/participants' | '/timing' | '/results/$participantId' | '/results'
  id:
    | '__root__'
    | '/'
    | '/participants'
    | '/timing'
    | '/results/$participantId'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParticipantsRoute: typeof ParticipantsRoute
  TimingRoute: typeof TimingRoute
  ResultsParticipantIdRoute: typeof ResultsParticipantIdRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timing': {
      id: '/timing'
      path: '/timing'
      fullPath: '/timing'
      preLoaderRoute: typeof TimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$participantId': {
      id: '/results/$participantId'
      path: '/results/$participantId'
      fullPath: '/results/$participantId'
      preLoaderRoute: typeof ResultsParticipantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParticipantsRoute: ParticipantsRoute,
  TimingRoute: TimingRoute,
  ResultsParticipantIdRoute: ResultsParticipantIdRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
